CC=g++
CFLAGS=-c -Wall
SFML=C:/Users/fuerchter/Downloads/FULLSFML3
RAPIDXML=C:/Users/fuerchter/Downloads/rapidxml-1.13/rapidxml-1.13

all : main.o Level.o Map.o
	$(CC) main.o Level.o Map.o -L$(SFML)/lib -lsfml-graphics -lsfml-window -lsfml-system
	
main.o : main.cpp Level.h Level.cpp
	$(CC) $(CFLAGS) main.cpp -I$(SFML)/include -I$(RAPIDXML)
	
Level.o : Level.h Level.cpp Map.h Map.cpp
	$(CC) $(CFLAGS) Level.cpp -I$(SFML)/include -I$(RAPIDXML)
	
Map.o : Map.h Map.cpp
	$(CC) $(CFLAGS) Map.cpp -I$(SFML)/include -I$(RAPIDXML)